//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstActualMVC.Models.ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_orders
    {
        [Key]
        public decimal ORD_NO { get; set; }
        public decimal PURCH_AMT { get; set; }
        public System.DateTime ORD_DATE { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal SALESMAN_ID { get; set; }
    }
}
